sudo: false
language: node_js
node_js:
  - "8"
branches:
  only:
    - master
notifications:
  email: false
script:
  - npm run validate
  - npm run build
after_success:
  - npm run report-coverage
  - npm install -g travis-deploy-once
  - travis-deploy-once "npm run semantic-release"
  